version: "3.9"
services:
  redis:
    image: redis 
    volumes:
      - ./counter-app/logs_data:/var/log
  counter-app:
    build: ./counter-app
    restart: always
    ports:
      - 6379:6379
    environment:
      - PORT=6379
      - REDIS_URL=redis://redis:6379
    links: 
      - redis
  mongodb:
    image: mongo
    restart: always
    expose:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD:-password}
      - MONGO_INITDB_DATABASE=${DB_NAME:-books_db}
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${DB_USERNAME:-root}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${DB_PASSWORD:-password}
    depends_on:
      - mongodb    
  node-books-app:
    build: .
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - COUNTER_API_HOST=counter-app://counter-app:6379
      - DB_USERNAME=${DB_USERNAME:-root}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - DB_NAME=${DB_NAME:-books_db}
      - DB_HOST=mongodb://mongodb:27017
    depends_on: 
      - counter-app
      - mongodb
volumes:
  logs_data: {}